version: "3.9"
services:
  loki:
    image: grafana/loki:2.5.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      cloud-native:
        ipv4_address: 10.5.0.99
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker-compose-config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./docker-compose-config/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - cloud-native
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker-compose-config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - cloud-native
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    networks:
      - cloud-native
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - cloud-native
  zipkin:
    image: "openzipkin/zipkin"
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - cloud-native
  jaeger:
    image: jaegertracing/all-in-one:1.22
    container_name: jaeger    
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9412
    ports:
      - "16686:16686"
    networks:
      - cloud-native
  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
    networks:
      - cloud-native
networks:
  cloud-native :
    driver: bridge
    name: cloud-native
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
          

  
