replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: alpine

containerPort: 5000
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  dapr.io/enabled: "true"
  dapr.io/app-id: "notification"
  dapr.io/app-port: "5000"
  dapr.io/config: "cloud-native-sample"
  prometheus.io/scrape: 'true'
  prometheus.io/port: '5000'

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: 
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 200Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
