apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders
  namespace: cloud-native-sample
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    secretKeyRef:
      name: rabbit
      key: connectionstring
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: sub-new-orders
spec:
  topic: new_orders
  route: /orders
  pubsubname: orders
scopes:
- shipping
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: sub-processed-orders
spec:
  topic: processed_orders
  route: /orders/processed
  pubsubname: orders
scopes:
- notification
