apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      # todo!: here we've to verify networking capabilities with docker-compose so that containers are able access ports on the host
      endpointAddress: "http://localhost:9412/api/v2/spans"
