apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <string> url
  url: http://prometheus:9090
  editable: true
