apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification.fullname" . }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-notification
      protocol: TCP
      name: http
  selector:
    {{- include "notification.selectorLabels" . | nindent 4 }}
