apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: zipkin
  labels:
    app: zipkin
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: ziphttp
