apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: cloud-native-sample
  namespace: cloud-native-sample
spec:
  tracing:
      samplingRate: "1"
      zipkin:
        endpointAddress: http://zipkin.zipkin.svc.cluster.local:9411/api/v2/spans
