name: Generate ACR token password
on:
  workflow_dispatch:
jobs:
  infra:
    name: "Generate ACR token password"
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.TERRAFORM_CLIENT_ID }}","clientSecret":"${{ secrets.TERRAFORM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TERRAFORM_TENANT_ID }}"}'
      - name: Generate ACR token password
        uses: azure/CLI@v1
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          TOKEN_NAME: ${{ secrets.ACR_TOKEN_NAME }}
        with: 
          inlineScript: |
            az account set --subscription ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
            az acr token credential generate -n $TOKEN_NAME -r $ACR_NAME --expiration-in-days 720 --password1

