name: Generate ACR token password
on:
  workflow_dispatch:
jobs:
  infra:
    name: "Generate ACR token password"
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.TERRAFORM_CLIENT_ID }}","clientSecret":"${{ secrets.TERRAFORM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TERRAFORM_TENANT_ID }}"}'
      - name: Generate ACR token password
        id: generateTokenPassword
        uses: azure/CLI@v1
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          TOKEN_NAME: ${{ secrets.ACR_TOKEN_NAME }}
        with: 
          inlineScript: |
            az account set --subscription ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
            tokenPassword=$(az acr token credential generate -n $TOKEN_NAME -r $ACR_NAME --expiration-in-days 720 --password1 --query "passwords[0].value -otsv")
            echo "::set-output name=value::$tokenPassword"
      - name: Update Token Password
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'ACR_TOKEN_PASSWORD'
          value: ${{ steps.generateTokenPassword.outputs.value}}
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
