name: "Authentication Service CI"
on:
  push:
    branches:
      - "main"
    paths:
      - "src/AuthenticationService"
  workflow_dispatch:
jobs:
  main:
    name: Build and Push AuthenticationService
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME}}.azurecr.io
          username: ${{ secrets.ACR_TOKEN_NAME }}
          password: ${{ secrets.ACR_TOKEN_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/authentication-service:${{ github.sha }} -t ${{ secrets.ACR_NAME }}.azurecr.io/authentication-service:${{ github.ref_name }}-latest
        working-directory: src/AuthenticationService
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/authentication-service:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/authentication-service:${{ github.ref_name }}-latest
        working-directory: src/AuthenticationService
