name: "Authentication Service CI"
on:
  push:
    branches:
      - "main"
    paths:
      - "src/AuthenticationService"
      - ".github/workflows/authenticationservice.*.yml"
  workflow_dispatch:
jobs:
  main:
    name: Build and Push AuthenticationService
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME}}.azurecr.io
          username: ${{ secrets.ACR_TOKEN_NAME }}
          password: ${{ secrets.ACR_TOKEN_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/authentication-service:${{ github.sha }} -t ${{ secrets.ACR_NAME }}.azurecr.io/authentication-service:${{ github.ref_name }}-latest
        working-directory: ./src/AuthenticationService
      - name: Install Dockle
        run: |
          VERSION=$(
          curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
          grep '"tag_name":' | \
          sed -E 's/.*"v([^"]+)".*/\1/' \
          ) && curl -L -o dockle.tar.gz https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz &&  \
          tar zxvf dockle.tar.gz
        working-directory: /tmp
      - name: Save Docker Image
        run: docker save ${{ secrets.ACR_NAME }}.azurecr.io/authentication-service:${{ github.sha }} -o authentication-service.tar
        working-directory: /tmp
      - name: Scan Docker Image
        run: |
          ./dockle -o results.json --exit-code 1 --exit-level WARN --input authentication-service.tar && \
          result=$(cat result.json) && \
          echo "::set-output name=value::$result"
        working-directory: /tmp
      - name: Report Vulnerabilities
        if: ${{ failure() }}
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Dockle Report for authentication-service:${{ github.sha }}
          body: |
            ## Dockle Report for authentication-service:${{ github.sha }}

            ```json
              ${{ steps.dockle.outputs.result }}
            ```
            Container image has not been pushed to Azure Container Registry.

          labels: |
            containers
            security
      - name: Push Docker Image
        if: ${{ success() }}
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/authentication-service:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/authentication-service:${{ github.ref_name }}-latest
        working-directory: ./src/AuthenticationService
