name: Azure Infrastructure CI
on:
  push:
    branches: ['main']
    paths:
      - 'azure/**'
  workflow_dispatch:
env:
  TERRAFORM_VERSION: 1.2.5
jobs:
  check:
    name: "Check repository contents"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: $TERRAFORM_VERSION
      - name: Check Format
        run: terraform fmt -no-color -check
        working-directory: ./azure
      - name: Initialize Terraform Project
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.TERRAFORM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
        working-directory: ./azure
      - name: Select Terraform Workspace
        run: terraform workspace select develop
        working-directory: ./azure
      - name: Validate Terraform Project
        run: terraform validate -no-color
        working-directory: ./azure
  reconcile:
    name: "Azure Infrastructure reconciliation"
    runs-on: ubuntu-latest
    needs: ['check']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: $TERRAFORM_VERSION
      - name: Initialize Terraform Project
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.TERRAFORM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
        working-directory: ./azure
      - name: Select Terraform Workspace
        run: terraform workspace select develop
      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.TERRAFORM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
        working-directory: ./azure
